clean:
	cd c_hybrid_same_file;make realclean
	cd c_partial_mock;make realclean
	cd cpp_filtered;make realclean
	cd cpp_partial_mock;make realclean
	cd cpp_signatures;make realclean
	cd cpp_test_hybrid_mock;make realclean
	cd cpp_test_no_inheritance;make realclean
	cd c_regression;make realclean
	cd c_test_hybrid_mock;make realclean
	cd fizzbuzz;make realclean
	cd fizzbuzz_pure_mock;make realclean
